apiVersion: v1
kind: Namespace
metadata:
  name: work360-employee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work360-employee-deployment
  namespace: work360-employee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: work360-employee
  template:
    metadata:
      labels:
        app: work360-employee
    spec:
      containers:
        - name: work360-employee
          image: kamil4921/work360-services-employee:master-085beea
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: work360-employee-service
  namespace: work360-namespace
spec:
  selector:
    app: work360-employee
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer