apiVersion: v1
kind: Namespace
metadata:
  name: work360-employee

---
# Persistent Volume (PV) and Claim (PVC) for PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: work360-employee
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: work360-employee
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: work360-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "exec pg_isready -h localhost -U postgres"
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# PostgreSQL Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: work360-employee
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work360-employee-deployment
  namespace: work360-employee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: work360-employee
  template:
    metadata:
      labels:
        app: work360-employee
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z postgres-db 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done;']
      containers:
        - name: work360-employee
          image: kamil4921/work360-services-employee:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---
# Application Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: work360-employee-lb
  namespace: work360-employee
spec:
  selector:
    app: work360-employee
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer