apiVersion: v1
kind: Namespace
metadata:
  name: work360-employee
---
# BEGIN PVC TODO: doczytac o storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: work360-employee
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
# END
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work360-employee-deployment
  namespace: work360-employee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: work360-employee
  template:
    metadata:
      labels:
        app: work360-employee
    spec:
      containers:
        - name: work360-employee
          image: kamil4921/work360-services-employee:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
#BEGIN POSTGRES Zalezne od PVC
        - name: postgresDb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
#END
---
apiVersion: v1
kind: Service
metadata:
  name: work360-employee-lb
  namespace: work360-employee
spec:
  selector:
    app: work360-employee
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer